1604051537913	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1604051537971	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1604051650185	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1604051650185	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1604051650192	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1604051650197	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1604051790240	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1604051790241	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1604051790260	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1604051790273	Sync.Service	DEBUG	User-Agent: Firefox/82.0 (Linux x86_64) FxSync/1.84.0.20201014125134.desktop
1604051790273	Sync.Service	INFO	Starting sync at 2020-10-30 15:26:30 in browser session 0uQbe4YQhDPE
1604051790274	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1604051790282	Sync.Status	INFO	Resetting Status.
1604051790282	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1604051790284	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1604051790284	FirefoxAccounts	DEBUG	getOAuthToken enter
1604051790285	FirefoxAccounts	TRACE	getCachedToken returning cached token
1604051790285	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1604051790286	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1604051790301	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1604051790302	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1604051790325	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/174286250/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1604051790331	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1604051790331	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1604051790331	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1604051790332	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1604051790334	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
